### ISSUE TITLE
Streamline debugging of Compute Board

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/shepherd_bms#10]
This ticket is broad, since we can't anticipate what things we might want to use to make debugging easier. Some stuff that might be useful could be using enumerators to define what process the segment goes through at each step, or creating fault codes, etc

**Comment by dyldonahue** [comment]
Here's the scoop: 

if something goes wrong in our code, the code will stop executing somewhere. For right now (though we can make it more robust in the future), simply placing serial prints in tactical locations throughout the code can help us figure out where the code stops executing. 

For this ticket, place a bunch of these prints throughout compute related stuff (compute.cpp) and make them descriptive so that we know where each one corresponds to.

Also, we don't want these executing all the time, only when we debug. To fix this, add ifdef guards. (to see an example of how this works, check main.cpp, and platformio.ini to see how those macros are initialized)
