### ISSUE TITLE
Streamline debugging for state machine

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/shepherd_bms#18]
This ticket is broad, but relates to making the state machine easier to debug/fix if something goes awry and we need to fix it quickly. This might include creating fault enumerators, ways of outputting what state we are in if we fault, etc

**Comment by dyldonahue** [comment]
Here's the scoop: 

if something goes wrong in our code, the code will stop executing somewhere. For right now (though we can make it more robust in the future), simply placing serial prints in tactical locations throughout the code can help us figure out where the code stops executing. 

For this ticket, place a bunch of these prints throughout segment related stuff (segment.cpp) and make them descriptive so that we know where each one corresponds to.

Also, we don't want these executing all the time, only when we debug. To fix this, add ifdef guards. (to see an example of how this works, check main.cpp, and platformio.ini to see how those macros are initialized)

**Comment by dyldonahue** [comment]
Here's the scoop: 

if something goes wrong in our code, the code will stop executing somewhere. For right now (though we can make it more robust in the future), simply placing serial prints in tactical locations throughout the code can help us figure out where the code stops executing. 

For this ticket, place a bunch of these prints throughout statemachine related stuff (Statemachine.cpp) and make them descriptive so that we know where each one corresponds to.

Also, we don't want these executing all the time, only when we debug. To fix this, add ifdef guards. (to see an example of how this works, check main.cpp, and platformio.ini to see how those macros are initialized)
